### ISSUE TITLE
AIFT project

### ISSUE THREAD

**Issue by chaeynii** [chaeynii/aift-project#1]
team 8

**Comment by songyejin123** [comment]
환경변수 설정오류
-가상환경 32비트로 설정 후에 필요 패키지 설치후 목록을 확인했을 때 있다고 뜨지만 아래와 같이 모듈이 없다고 뜸.
- 컴퓨터를 새로 시작할 때마다 파이썬 파일이 격리소로 이동되어 가상환경자체가 삭제되지도 않고 새로 만들어서 임시방편으로 해결

![오류](https://user-images.githubusercontent.com/87214483/203333418-f8b75fd5-5fda-4cd3-b810-faed273ce126.png)
